/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.8/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

val lwjglVersion = "3.3.5"
val lwjglNatives = "natives-macos-arm64"

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    mavenLocal() // ローカルリポジトリを追加
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation("org.junit.jupiter:junit-jupiter:5.8.1")

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:31.1-jre")

    implementation(platform("org.lwjgl:lwjgl-bom:$lwjglVersion"))

    implementation("org.lwjgl:lwjgl")
    implementation("org.lwjgl:lwjgl-assimp")
    implementation("org.lwjgl:lwjgl-glfw")
    implementation("org.lwjgl:lwjgl-openal")
    implementation("org.lwjgl:lwjgl-opengl")
    implementation("org.lwjgl:lwjgl-stb")

    runtimeOnly("org.lwjgl:lwjgl") {
        artifact {
            name = "lwjgl"
            classifier = lwjglNatives
        }
    }
    runtimeOnly("org.lwjgl:lwjgl-assimp") {
        artifact {
            name = "lwjgl-assimp"
            classifier = lwjglNatives
        }
    }
    runtimeOnly("org.lwjgl:lwjgl-glfw") {
        artifact {
            name = "lwjgl-glfw"
            classifier = lwjglNatives
        }
    }
    runtimeOnly("org.lwjgl:lwjgl-openal") {
        artifact {
            name = "lwjgl-openal"
            classifier = lwjglNatives
        }
    }
    runtimeOnly("org.lwjgl:lwjgl-opengl") {
        artifact {
            name = "lwjgl-opengl"
            classifier = lwjglNatives
        }
    }
    runtimeOnly("org.lwjgl:lwjgl-stb") {
        artifact {
            name = "lwjgl-stb"
            classifier = lwjglNatives
        }
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass.set("jp.ac.uryukyu.ie.e245719.Main")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
